# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kassa', '0006_auto_20150829_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='kassaevent',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
